### ISSUE TITLE
Affinity not working?

### ISSUE THREAD

**Issue by zaks** [OT-CONTAINER-KIT/helm-charts#10]
I'm not sure if this works

https://github.com/OT-CONTAINER-KIT/helm-charts/blob/1a3e3c45317297821d07c7e71525d9a1b3a96120/charts/redis-cluster/templates/redis-cluster.yaml#L24

I get following error when I specify it and try to upgrade the helm chart:

Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(RedisCluster.spec.redisFollower): unknown field "affinity" in in.opstreelabs.redis.redis.v1beta1.RedisCluster.spec.redisFollower, ValidationError(RedisCluster.spec.redisLeader): unknown field "affinity" in in.opstreelabs.redis.redis.v1beta1.RedisCluster.spec.redisLeader]

**Comment by iamabhishek-dubey** [comment]
This should be fixed now
