### ISSUE TITLE
Deploying redis-cluster raises permission denied issue of "/data/node.conf" file with default configurations

### ISSUE THREAD

**Issue by sv6375261073** [OT-CONTAINER-KIT/helm-charts#115]
redis-cluster version 0.15.0
configs: default
error: permission denied /data/node.conf file.

**Comment by sv6375261073** [comment]
This issue can be fixed by changing the user in security contexts in statefulset "redis-cluster" which is "{}" by default.

spec:
  securityContext:
    runAsUser: 1099
    runAsGroup: 1099
    fsGroup: 1099

**Comment by sv6375261073** [comment]
Please do the changes in statefulset as it should not happen even in default config also.

**Comment by sv6375261073** [comment]
@shubham-cmyk can you please provide update for it, ??

**Comment by shubham-cmyk** [comment]
@sv6375261073 

Have you tried using latest helm chart version v0.15.3

**Comment by sv6375261073** [comment]
Is that released? 0.15.0 was the default latest. And i am using the same.
If 0.15.3 is released will upgrade and test it.

**Comment by shubham-cmyk** [comment]
Yes @sv6375261073 This might be due to the CRD are not updated. 
Helm has a issue it don't update the crd so you might have to apply that. 
If you use helm upgrade then this issue might arise if you uninstall the crd and install again then it would be fine

**Comment by sv6375261073** [comment]
Yes, upgraded to 0.15.3 and resolved the issue.

Thanks for your help
