### ISSUE TITLE
Cluster mode not enabled (All leader and follower are in master type and 0 connection with slave in all )

### ISSUE THREAD

**Issue by sv6375261073** [OT-CONTAINER-KIT/helm-charts#117]
version 0.15.0

I tried failover testing also but no effect because all leader or follower are master type there is no pod with slave type so failover is also not working.

After deleting master type pod comes with master type only.

**Comment by sv6375261073** [comment]
<img width="539" alt="image" src="https://github.com/OT-CONTAINER-KIT/helm-charts/assets/36235393/8e4892f1-56da-44d3-b913-a93afb001b62">

**Comment by shubham-cmyk** [comment]
which CR are you using ?

**Comment by shubham-cmyk** [comment]
You need to use redis-cluster independently the redis-sentinel mode is for the redis-replication. 

Also please upgrade the charts to v0.15.2 the latest of all you can find

**Comment by sv6375261073** [comment]
This is fixed in 0.15.3 version.

Thanks
