### ISSUE TITLE
[Feature] : Add Cert-Manager as the chart dependency of the Redis-Operator 

### ISSUE THREAD

**Issue by shubham-cmyk** [OT-CONTAINER-KIT/helm-charts#129]
Since we have introduced a cert-manger.yaml in the template this would require the helm chart of cert-manager so we could add this as a dependency here.

**Comment by ppborah** [comment]
@shubham-cmyk, assign this to me

**Comment by Routhinator** [comment]
Hi @shubham-cmyk 

I'm not sure why this was added but this was unexpected, not documented - and very bad

https://github.com/OT-CONTAINER-KIT/helm-charts/commit/4c3018d4c0797c6f1619f91fc38092ef68e874b6 


What this resulted in is this chart bringing in and installing a SECOND cert-manager into my cluster and the two went to war - replacing working certificates and exhausting letsencrypt API requests in a matter of days!

This should not be a dependency of this chart. There should be a documented need for a cert-request. A redis chart should not be prescribing certificate management or bringing cert manager into clusters where cert-manager already exists..
