### ISSUE TITLE
`redis-cluster` imagePullSecret

### ISSUE THREAD

**Issue by davidroman0O** [OT-CONTAINER-KIT/helm-charts#138]
Looking at the [redis-cluster readme](https://github.com/OT-CONTAINER-KIT/helm-charts/blob/50a7aa7a90ef9dffce2321314c148893fd1401c2/charts/redis-cluster/README.md?plain=1#L35C1-L36C1), it says that we can use `imagePullSecrets` as an array but i see it used nowhere in the charts.

Am I wrong? Did I missed something?

**Comment by shubham-cmyk** [comment]
I think this section is not included in the chart. 
I would fix that it would be available from the chart version v0.15.5
