### ISSUE TITLE
redis-replication conflicting spec with CRD version

### ISSUE THREAD

**Issue by jwitko** [OT-CONTAINER-KIT/helm-charts#150]
**Does this issue reproduce with the latest release?**
Yes

**What did you do?**
Standard deployment

**What did you expect to see?**
podSecurityContext applied to statefulset for redis-replication chart

**What did you see instead?**
The helm chart was updated to take in the value `podSecurityContext` instead of `securityContext` and it provides it as such to the `RedisReplication` spec.  However the CRD version is still `v1beta1`, which does not recognize `.spec.podSecurityContext`.  This results in the inability to deploy

**Comment by jwitko** [comment]
This relates to #105

**Comment by shubham-cmyk** [comment]
@jwitko 

This is not conflict we have a conversion webhook added in the helm chart to support the we need conversion.

**Comment by shubham-cmyk** [comment]
@jwitko 

The Helm chart of redis replication was not updated. I would push that

**Comment by jwitko** [comment]
@shubham-cmyk I see the helm chart was not updated but I'm not clear on your last sentence `I would push that`?  Are you saying you will update and push the change?

**Comment by shubham-cmyk** [comment]
@jwitko I have released the charts can you confirm if the error is still there
