### ISSUE TITLE
[BUG] Remove Cert-manager as a dependency of redis-operator

### ISSUE THREAD

**Issue by Routhinator** [OT-CONTAINER-KIT/helm-charts#166]
https://github.com/OT-CONTAINER-KIT/helm-charts/issues/129#issuecomment-1764735418 

As per my comment here, this chart unexpectedly installed a SECOND cert-manager instance in my cluster without mentioning such in the docs. 

A redis operator should not be prescribing certificate management or installing cert-manager into clusters where cert-managers already exist. This caused two instances of cert-manager to war over certificates in my cluster, exhausting API requests to letsencrypt and breaking applications for multiple domains for the next week while I wait for the api limit to cool off.

This needs to be removed. If this chart needs certificate requests, it should add requests, and DOCUMENT the need for cert-manager

**Comment by shubham-cmyk** [comment]
> Doesn't look like 0.15.9 does it. Which is good.

https://github.com/OT-CONTAINER-KIT/helm-charts/blob/main/charts/redis-operator/templates/cert-manager.yaml#L1
The installation of certificates is not enabled in the values.yaml 
also cert-manger should not be installed anyway here : 
https://github.com/OT-CONTAINER-KIT/helm-charts/blob/main/charts/redis-operator/Chart.yaml#L28

The default is marked `false`

https://github.com/OT-CONTAINER-KIT/helm-charts/blob/main/charts/redis-operator/values.yaml#L54

**Comment by shubham-cmyk** [comment]
`chart makes good sense and is a good pattern. Installing cert-manager - not so much.`

This point seems to be valid. I could consider dropping the dependency here.

**Comment by genofire** [comment]
could we create an option to just deploy the Certificate (and use an own clusterissuer)?
