### ISSUE TITLE
Issue with setting auth values in helm values file for current version of redis-cluster.

### ISSUE THREAD

**Issue by maccavelli** [OT-CONTAINER-KIT/helm-charts#169]
**Does this issue reproduce with the latest release?**
Yes
**What operating system and processor architecture are you using (`kubectl version`)?**
Openshift 4.12
<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version 4.11.29

</pre></details>

**What did you do?**
In setting up the values file for our environment I kept having it blow up telling me that an expected value was missing in a position in the values file that made no sense. I worked from the bottom of the values file and when I got to the top and set `  redisSecret:
    secretName: ""
    secretKey: ""`
It blows up the chart, which fails to deploy. Remove the values for the secretname and secretkey and leave those values empty, the chart will deploy.

**What did you expect to see?**
A deployed cluster.
**What did you see instead?**
It blows up about missing values at weird places in the values file.

I reverted back to 0.15.3 and it works fine.

**Comment by diffuse** [comment]
Try this with v0.15.10:
```yaml
redisSecret:
  name: redis-secret
  key: password
```
