### ISSUE TITLE
redisConfig is not well generated

### ISSUE THREAD

**Issue by mrhovunping** [OT-CONTAINER-KIT/helm-charts#178]
**Does this issue reproduce with the latest release?**
Yes 

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.21.9
WARNING: version difference between client (1.28) and server (1.21) exceeds the supported minor version skew of +/-1
</pre></details>

**What did you do?**

<details><summary><code>Set values.yml with externalConfig</code> Code</summary><br><pre>
externalConfig:
  enabled: true
  data: |
    sentinel auth-pass myMaster xxxx
</pre></details>

Helm with 
**What did you expect to see?**
<pre>
  redisConfig:
    additionalRedisConfig: "config-ext-config"
</pre>
**What did you see instead?**
<pre>
    redisConfig:
      additionalRedisConfig: "config-ext-config"
</pre>

Error come from :  [code](https://github.com/OT-CONTAINER-KIT/helm-charts/blob/c54e65c3fa10ffacc6d7a83584b864f38600f0c4/charts/redis-sentinel/templates/redis-sentinel.yaml#L52)

There is too much indent and element not well place

**What did you expect to see?**
<pre>
  {{- if .Values.externalConfig.enabled }}
   redisConfig:
     additionalRedisConfig: "{{ .Values.redisSentinel.name | default .Release.Name }}-ext-config"
  {{- end }}
</pre>
**What did you see instead?**
<pre>
  {{- if .Values.externalConfig.enabled }}
    redisConfig:
      additionalRedisConfig: "{{ .Values.redisSentinel.name | default .Release.Name }}-ext-config"
  {{- end }}
</pre>

**Comment by shubham-cmyk** [comment]
@mrhovunping Would you consider opening a PR for the same here
