### ISSUE TITLE
imagePullSecrets not available for redis-operator helm chart

### ISSUE THREAD

**Issue by alita1991** [OT-CONTAINER-KIT/helm-charts#188]
**Does this issue reproduce with the latest release?**

yes

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: v1.29.3
</pre></details>

**What did you do?**
I fetched the redis-operator helm chart and looked over the "imagePullSecrets" field, that is required for authentication with private registries.

**What did you expect to see?**

A possible way to configure the redis-operator to fetch the images from private registries.

**What did you see instead?**

imagePullSecrets field is not present.

**Comment by civkule** [comment]
any updates on this issue?
