### ISSUE TITLE
Broken chart

### ISSUE THREAD

**Issue by LvLs9** [OT-CONTAINER-KIT/helm-charts#19]
https://github.com/OT-CONTAINER-KIT/helm-charts/blob/be516fec7ec71fd04efac8ff76d0b0e15ec67982/charts/redis-operator/crds/redis-cluster.yaml#L3427

**Comment by dm3ch** [comment]
Linking issue describing same problem - https://github.com/OT-CONTAINER-KIT/helm-charts/issues/18#issue-1133108201
