### ISSUE TITLE
error pulling image quay.io/opstree/redis-operator:v0.16.0

### ISSUE THREAD

**Issue by vfiftyfive** [OT-CONTAINER-KIT/helm-charts#192]
Hi, it looks like something is wrong with the latest helm chart or with quay. It's trying to pull redis-operator:v0.16.0 from quay. But there's no such image hosted there. That tag doesn't currently exist in this registry.
As a result, Kubelet returns 
`Failed to pull image "quay.io/opstree/redis-operator:v0.16.0": rpc error: code = NotFound desc = failed to pull and unpack image
"quay.io/opstree/redis-operator:v0.16.0": failed to resolve reference "quay.io/opstree/redis-operator:v0.16.0": quay.io/opstree/redis-operator:v0.16.0: not found`
If I modify the version to v0.15.1 in the image of the pod template in the deployment, then it works.

Cheers,

Nic

**Comment by EStork09** [comment]
Someone updated the helm chart before the image was pushed. [#908](https://github.com/OT-CONTAINER-KIT/redis-operator/issues/908) is tracking the issue currently.

**Comment by drivebyer** [comment]
Image built in: ghcr.io/ot-container-kit/redis-operator/redis-operator:v0.17.0.
New operator chart: https://github.com/OT-CONTAINER-KIT/helm-charts/releases/tag/redis-operator-0.16.1.
