### ISSUE TITLE
Helm Chart CRDs for Redis Operator are not up to date

### ISSUE THREAD

**Issue by alita1991** [OT-CONTAINER-KIT/helm-charts#197]
**Does this issue reproduce with the latest release?**
Yes

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: v1.29.3
</pre></details>

**What did you do?**
Installed the latest redis-operator helm chart (tested with the helm chart from helm-charts repo and also with the one from redis-operator repo)

**What did you expect to see?**
`redisReplicationPassword` field should exist in RedisSentinel CRD

**What did you see instead?**
`redisReplicationPassword` field is not found in RedisSentinel CRD

**Note**
The CRD update is important to allow Redis Sentinel to connect to Redis Replication, when auth is activated

**Comment by drivebyer** [comment]
The Redis Operator Helm chart is maintained by the team at https://github.com/OT-CONTAINER-KIT/redis-operator/tree/master/charts/redis-operator. If you have any issues, feel free to submit them to the Redis Operator repository. Thank you!

**Comment by alita1991** [comment]
Hi @drivebyer, I even looked into the helm chart from the Redis Operator repository, we have the same issue there, the CRDs were not updated.

**Comment by drivebyer** [comment]
Absolutely, the CRD hasn't been updated yet. We'll make sure to update it following the next image release. @alita1991

**Comment by pasztorl** [comment]
@drivebyer I see that redis-operator version now 0.17.0. Please also push an image to https://quay.io/repository/opstree/redis-operator because the latest version is 0.15.1
Thanks!

**Comment by drivebyer** [comment]
@pasztorl, actually I do not have permission for quay.io.
