### ISSUE TITLE
quay.io/opstree/redis-operator:v0.18.0 image tag v0.18.0 not available

### ISSUE THREAD

**Issue by RameshPSIT** [OT-CONTAINER-KIT/helm-charts#219]
**Does this issue reproduce with the latest release?**
Yes

**What did you see?**
ImagePullBackOff error as tag v0.18.0 is not available in image repository quay.io/opstree/redis-operator https://quay.io/repository/opstree/redis-operator?tab=tags&tag=latest

**What did you expect to see?**
Please make image available with tag v0.18.0. Or let us know if we need to point to some other image registry.

**Comment by drivebyer** [comment]
see https://github.com/OT-CONTAINER-KIT/redis-operator/tree/master/charts/redis-operator#values @EdagPSIT
