### ISSUE TITLE
Cannot connect to cluster using python redis client with password

### ISSUE THREAD

**Issue by JC1DA** [OT-CONTAINER-KIT/helm-charts#24]
Hi, I can login into the cluster using redis-cli with password.
But when using python client to login, I got this error

redis.exceptions.ResponseError: AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?

I found this [article](https://medium.com/@umutuluer/resolving-the-err-client-sent-auth-but-no-password-is-set-error-b81438d10843) telling that "requirepass" is not set in the redis.conf file.

I can fix this by using YAML config file described [here](https://github.com/OT-CONTAINER-KIT/redis-operator/tree/master/example/external_config) but I'm wondering if we can do this via helm chart?

Thank you

**Comment by iamabhishek-dubey** [comment]
External config option is supported now, so you can use that to customize redis config.
