### ISSUE TITLE
Failed to install redis chart

### ISSUE THREAD

**Issue by salleman33** [OT-CONTAINER-KIT/helm-charts#26]
Hi, 
I got this error : 
`  Error: Failed to render chart: exit status 1: Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Redis.spec.kubernetesConfig): unknown field "serviceType" in in.opstreelabs.redis.redis.v1beta1.Redis.spec.kubernetesConfig`

Thanks

**Comment by dthstrk** [comment]
Just got the same error when installing the chart via rancher:
```
helm install --namespace=backend --timeout=10m0s --values=/home/shell/helm/values-redis-0.9.0.yaml --version=0.9.0 --wait=true redis /home/shell/helm/redis-0.9.0.tgz

Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Redis.spec.kubernetesConfig): unknown field "serviceType" in in.opstreelabs.redis.redis.v1beta1.Redis.spec.kubernetesConfig 
```
K8s Version: 1.21.9
Redis-Operator Version: 0.10.1

Happy to help if I can give more information.

**Comment by chriskolenko** [comment]
From my own debugging. 

serviceType isn't part of the CRD spec for redis or redis-cluster (Was removed a while back not sure why) and the redis and redis-cluster haven't been updated to reflect this. 

My work around. 

```
// Pull the chart down 
helm pull ot-helm/redis --untar

// Generate yaml locally
mkdir -p ./output
helm template --output-dir ./output ./redis

// Remove clusterType
// I just used vs code for this. 

kubectl -n {my-namespace} apply -f ./output/redis/templates/redis-standalone.yaml
```

**Comment by iamabhishek-dubey** [comment]
Updated and fixed

**Comment by salleman33** [comment]
Hi, 
the problem is not fixed. 
redis-operator CRD doesn't contains serviceType. Redis template does ! I don't see anything in recents commits about this problem...
