### ISSUE TITLE
Using imagePullSecrets when using private registry

### ISSUE THREAD

**Issue by mostafabayat** [OT-CONTAINER-KIT/helm-charts#27]
We want to use redis operator in our cluster but we use private registry to use images. can you add imagePullSecrets to your templates?

**Comment by rganeshsharma** [comment]
@mostafabayat Can you try adding this :
```
redisOperator:
imagePullSecrets:
 - name: <secret>
```

**Comment by mostafabayat** [comment]
> @mostafabayat Can you try adding this :
> 
> ```
> redisOperator:
> imagePullSecrets:
>  - name: <secret>
> ```

@rganeshsharma 
Thanks for your reply. but I mean using imagePullSecrets in redis standalone, not redisOperator itself.

**Comment by rganeshsharma** [comment]
@mostafabayat Sorry about that my bad.
Yes we can use ImagePullSecrets in redis standalone and it pulls the Image successfully, but we may land up in livenessProbe and readinessProbe failures if yuo are using custom image through.

Also I am unable to use redis-cluster charts as it says "Fails to download charts" the repo is added
