### ISSUE TITLE
securityContext is not accepted in mongodb-cluster helm chart p

### ISSUE THREAD

**Issue by jjnavsofs0** [OT-CONTAINER-KIT/helm-charts#28]
The mongodb  cluster doesn't accept securityContext object variable in kubeconfig section. The operator says its possible but actually its not happening.

**Comment by iamabhishek-dubey** [comment]
Have you tried using manifest as well?

**Comment by iamabhishek-dubey** [comment]
This is fixed in the new version of MongoDB operator
