### ISSUE TITLE
Unable to connect to Redis External Load Balancer Service

### ISSUE THREAD

**Issue by Sj1218305** [OT-CONTAINER-KIT/helm-charts#44]
I have created an EKS cluster with the Managed Node Groups.
 
Recently, I have deployed Redis as an external Load Balancer service. 
I am trying to to set up an authenticated connection to it via NodeJS and Python microservices but I am getting Connection timeout error.
However, I am able to enter into the deployed redis container and execute the redis commands. 
Also, I was able to do the same when I deployed Redis on GKE. 

Have I missed some network configurations to allow traffic from external resources?
The subnets which the EKS node is using are all public. 
Also, while creating the Amazon EKS node role, I have attached 3 policies to this role as suggested in the [doc][1] - 
- AmazonEKSWorkerNodePolicy
- AmazonEC2ContainerRegistryReadOnly
- AmazonEKS_CNI_Policy

It was also mentioned that - 
We recommend assigning the policy to the role associated to the Kubernetes service account instead of assigning it to this role.
Will attaching this to the Kubernetes service account, solve my problem ?
Also, here is the guide that I used for deploying redis - 
https://ot-container-kit.github.io/redis-operator/guide/setup.html#redis-standalone

  [1]: https://docs.aws.amazon.com/eks/latest/userguide/create-node-role.html#create-worker-node-role

**Comment by iamabhishek-dubey** [comment]
This is more of a EKS related issue that requires k8s level of troubleshooting.
