### ISSUE TITLE
charts/redis-cluster: redisCluster.clusterVersion=v6 doesn't provision v6 cluster

### ISSUE THREAD

**Issue by armujahid** [OT-CONTAINER-KIT/helm-charts#51]
if we set `redisCluster.clusterVersion` to v6 then it still provisions v7.0.5 redis cluster. Is this a bug or intended behavior?
Note that if I also set `tag: v6.2.5` then v6 cluster in provisioned that's why this is not a blocking issue.

**Comment by iamabhishek-dubey** [comment]
Yes @armujahid v6.> should be clusterVersion of v6
