### ISSUE TITLE
Timeline for release supporting v0.13.0

### ISSUE THREAD

**Issue by nick-at-UW** [OT-CONTAINER-KIT/helm-charts#57]
I was just curious as to the timeline for the helm chart to support v0.13.0 as there are some features we'd like to implement.

Is there a pre-release/devel branch anywhere that work can be tracked or leveraged?

**Comment by shubham-cmyk** [comment]
@iamabhishek-dubey  Can you release v0.13.0 for the helm we have that in the operator. 

Related issue : https://github.com/OT-CONTAINER-KIT/redis-operator/issues/400

**Comment by iamabhishek-dubey** [comment]
Released https://github.com/OT-CONTAINER-KIT/helm-charts/releases
