### ISSUE TITLE
unknown field "pdb" in in.opstreelabs.redis.redis.v1beta1.RedisCluster.spe

### ISSUE THREAD

**Issue by zhzblackc12** [OT-CONTAINER-KIT/helm-charts#64]
after
helm upgrade redis-cluster ot-helm/redis-cluster   --set redisCluster.clusterSize=3 --install --namespace ot-operators
got error: 
unknown field "pdb" in in.opstreelabs.redis.redis.v1beta1.RedisCluster.spec

**Comment by bangpc** [comment]
@zhzblackc12 This pull request solve your issue 
https://github.com/OT-CONTAINER-KIT/helm-charts/pull/63

**Comment by zhzblackc12** [comment]
> @zhzblackc12 This pull request solve your issue #63

But not yet

**Comment by CrossainQi** [comment]
> @zhzblackc12 This pull request solve your issue #63

same to me, the pull request doesn't help

**Comment by ZleFox** [comment]
doesn't work with redis-operator 0.14.0 too

**Comment by iamabhishek-dubey** [comment]
Fixed
