### ISSUE TITLE
Implementation of ACL configfile

### ISSUE THREAD

**Issue by LeifSchumi** [OT-CONTAINER-KIT/helm-charts#67]
I can't find a way to integrate an external aclfile to configure users using the helm chart for a redis-cluster. Is there a way to integrate it? I thought about using the externalConfig parameter in the values.yaml, but there's no documentation for this parameter.

**Comment by shubham-cmyk** [comment]
Read this : https://github.com/OT-CONTAINER-KIT/redis-operator/tree/master/example/acl_config
