### ISSUE TITLE
redis-operator 0.14.0 uses 0.12.0 images

### ISSUE THREAD

**Issue by prezhdarov** [OT-CONTAINER-KIT/helm-charts#69]
Hi Guys, 

This may be as designed, yet I think it looks more like typo - redis-operator chart v0.14.0 has image tag v0.12.0. 

Also seems like redis-sentinel images aren't public. Is that intentional? 

Thank you for the great work you do and take care,
Atanas

**Comment by iamabhishek-dubey** [comment]
Fixed
