### ISSUE TITLE
Redis operator is crashlooping after upgrade to v0.14.1 helm chart

### ISSUE THREAD

**Issue by ZleFox** [OT-CONTAINER-KIT/helm-charts#70]
I have a test setup with one cluster. I had to install it on version 0.12.0 for both operator and cluster nodes because version 0.13 was not installable due to  #64. I have kept the operator up-to-date as the issue was with updating the cluster only. Now after upgrading to 0.14.1(for the operator) and 0.14.0 for the cluster chart the cluster is running normally, but the operator is crashlooping 
here is the log: 
[redis-operator-f565f7b8b-cvxhf_redis-operator(2).log](https://github.com/OT-CONTAINER-KIT/helm-charts/files/10787151/redis-operator-f565f7b8b-cvxhf_redis-operator.2.log)
I can see two types of errors: 
1) CRD issues with the new sentinel feature 
2) changes in the statefulset which should be fixable by recreating the sts

**Comment by ZleFox** [comment]
the statefulset issue was setting the chart version in the selector.matchLabels. So on every upgrade it would have to be recreated. But the operator does not seem to be doing it. 
After fixing it - it still continued to restart because of the missing CRDs. 
After uninstalling the operator helm release  and installing it again it is now fixed. It would seem that on upgrade new CRDs are not installed.

**Comment by shubham-cmyk** [comment]
@ZleFox Yes on every upgrade CRD are not updated. 
Is your issue solved or you still face any problem.

**Comment by ZleFox** [comment]
yes, it is. I just wanted to report it as the upgrade process was not as generally expected.

**Comment by shubham-cmyk** [comment]
Thanks a lot @ZleFox
