### ISSUE TITLE
`redis-operator` 0.8.0 uses old CRDs

### ISSUE THREAD

**Issue by rcny** [OT-CONTAINER-KIT/helm-charts#9]
Hello!

https://github.com/OT-CONTAINER-KIT/helm-charts/tree/redis-operator-0.8.0/charts/redis-operator/crds uses the `0.7.0`'s CRDs. It makes impossible to use `redisLeader` and `redisFollower` affinity rules because they aren't supported in the old CRDs.

**Comment by walkamongus** [comment]
just ran into this as well trying to use the leader and follower config fields

**Comment by zaks** [comment]
Ouch. Same pain. I also raised issue #10 which can be de-duped against this.

**Comment by iamabhishek-dubey** [comment]
This is fixed now
